#! /usr/bin/env   node
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('请输入您的姓名：', (name) => {
  console.log(`您好3，${name}！`);
  rl.close();
});
